name: CI/CD
on: push
jobs:
  windows-build:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - name: CMake Build
        shell: powershell
        run: |
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DBUILD_BOUNT_CORE_TESTS=ON --no-warn-unused-cli -S"./" -B"./build" -G "Visual Studio 17 2022" -T host=x64 -A x64
          cmake --build "./build" --config Release --target ALL_BUILD -j ([int]$env:NUMBER_OF_PROCESSORS+2) --
      
      # - name: Run Tests
      #   id: ctest
      #   continue-on-error: true
      #   shell: powershell
      #   run: ctest -C Release
      #   working-directory: "build"
